import Foundation
@testable import GISTools
import Testing

/// Buffer tests.
///
/// Two groups of tests:
///
/// 1. **Reference tests** using GeoJSON files generated by `turf.js`
///    (`@turf/buffer` + `@turf/jsts`). Expected outputs are in
///    `TestData/Buffer/` and comparisons use TOTAL AREA with a 5%
///    tolerance.
///
/// 2. **Ported Turf.js buffer tests** — input + expected-output files
///    from the `@turf/buffer` test suite. Each input has
///    `properties.{radius,units}` for the buffer distance.
///    Comparisons use 10% area tolerance.
struct BufferTests {

    // MARK: - Reference test helpers

    private func loadExpected(_ name: String) throws -> MultiPolygon {
        try TestData.multiPolygon(package: "Buffer", name: name)
    }

    private func checkArea(
        _ result: MultiPolygon,
        _ expected: MultiPolygon,
        tolerance: Double = 0.05
    ) {
        let resultArea = result.polygons.reduce(0) { $0 + $1.area }
        let expectedArea = expected.polygons.reduce(0) { $0 + $1.area }
        if expectedArea == 0 {
            #expect(resultArea == 0)
            return
        }
        let ratio = resultArea / expectedArea
        #expect(ratio > 1.0 - tolerance && ratio < 1.0 + tolerance,
                "Area ratio \(ratio) outside [\(1 - tolerance), \(1 + tolerance)]")
    }

    // MARK: - Turf helper methods

    private static func expectedArea(
        _ name: String,
        tolerance: Double = 0.10
    ) throws -> (area: Double, tolerance: Double) {
        let fc = try TestData.featureCollection(package: "Buffer/out", name: name)
        var total: Double = 0
        for feature in fc.features {
            guard feature.properties["stroke"] as? String == "#F00" else { continue }
            if let polygon = feature.geometry as? Polygon {
                total += polygon.area
            }
            else if let multiPolygon = feature.geometry as? MultiPolygon {
                total += multiPolygon.polygons.reduce(0) { $0 + $1.area }
            }
        }
        return (total, tolerance)
    }

    private static func bufferParams(_ name: String) throws -> (distance: Double, steps: Int) {
        let json = try TestData.stringFromFile(package: "Buffer/in", name: name)
        guard let data = json.data(using: .utf8),
              let dict = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return (GISTool.convertToMeters(50, .miles), 64) }

        let props = dict["properties"] as? [String: Any] ?? [:]
        let radius = props["radius"] as? Double ?? 50.0
        let units = props["units"] as? String ?? "miles"
        let steps = props["steps"] as? Int ?? 64

        let unit: GISTool.Unit
        switch units {
        case "meters", "metres": unit = .meters
        case "miles": unit = .miles
        default: unit = .miles
        }
        return (GISTool.convertToMeters(abs(radius), unit), steps)
    }

    // MARK: - Reference tests

    @Test func bufferedPoint() async throws {
        let point = Point(Coordinate3D(latitude: 47.56, longitude: 10.22))
        let result = try #require(point.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("PointResult"))
    }

    @Test func bufferedPoints() async throws {
        let multiPoint = try #require(MultiPoint([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(multiPoint.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("MultiPointResult"))
    }

    @Test func bufferedLineShort() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("LineRoundResult"))
    }

    @Test func bufferedLineShortFlatEnds() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkArea(result, try loadExpected("LineFlatResult"))
    }

    @Test func bufferedLineLong() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
            Coordinate3D(latitude: 47.60, longitude: 10.25),
            Coordinate3D(latitude: 47.65, longitude: 10.25),
            Coordinate3D(latitude: 47.70, longitude: 10.2),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("LongLineRoundResult"), tolerance: 0.15)
    }

    @Test func bufferedLineLongFlatEnds() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
            Coordinate3D(latitude: 47.60, longitude: 10.25),
            Coordinate3D(latitude: 47.65, longitude: 10.25),
            Coordinate3D(latitude: 47.70, longitude: 10.2),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkArea(result, try loadExpected("LongLineFlatResult"), tolerance: 0.25)
    }

    @Test func bufferedLines() async throws {
        let multiLineString = try #require(MultiLineString([
            [
                Coordinate3D(latitude: 47.56, longitude: 10.2),
                Coordinate3D(latitude: 47.56, longitude: 10.25),
            ],
            [
                Coordinate3D(latitude: 47.60, longitude: 10.25),
                Coordinate3D(latitude: 47.65, longitude: 10.25),
                Coordinate3D(latitude: 47.70, longitude: 10.2),
            ],
        ]))
        let result = try #require(multiLineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("MultiLineRoundResult"), tolerance: 0.25)
    }

    @Test func bufferedLinesFlatEnds() async throws {
        let multiLineString = try #require(MultiLineString([
            [
                Coordinate3D(latitude: 47.56, longitude: 10.2),
                Coordinate3D(latitude: 47.56, longitude: 10.25),
            ],
            [
                Coordinate3D(latitude: 47.60, longitude: 10.25),
                Coordinate3D(latitude: 47.65, longitude: 10.25),
                Coordinate3D(latitude: 47.70, longitude: 10.2),
            ],
        ]))
        let result = try #require(multiLineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkArea(result, try loadExpected("MultiLineFlatResult"))
    }

    @Test func bufferedPolygon() async throws {
        let polygon = try #require(Polygon([
            [
                Coordinate3D(latitude: 47.5, longitude: 10.2),
                Coordinate3D(latitude: 47.5, longitude: 10.25),
                Coordinate3D(latitude: 47.6, longitude: 10.35),
                Coordinate3D(latitude: 47.7, longitude: 10.25),
                Coordinate3D(latitude: 47.6, longitude: 10.15),
                Coordinate3D(latitude: 47.5, longitude: 10.2),
            ],
            [
                Coordinate3D(latitude: 47.52, longitude: 10.25),
                Coordinate3D(latitude: 47.56, longitude: 10.30),
                Coordinate3D(latitude: 47.65, longitude: 10.23),
                Coordinate3D(latitude: 47.6, longitude: 10.22),
                Coordinate3D(latitude: 47.52, longitude: 10.25),
            ],
        ]))
        let result = try #require(polygon.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("PolygonWithHoleResult"))
    }

    @Test func bufferedMultiPolygon() async throws {
        let multiPolygon = try #require(MultiPolygon([
            Polygon([
                [
                    Coordinate3D(latitude: 47.5, longitude: 10.2),
                    Coordinate3D(latitude: 47.5, longitude: 10.25),
                    Coordinate3D(latitude: 47.6, longitude: 10.35),
                    Coordinate3D(latitude: 47.7, longitude: 10.25),
                    Coordinate3D(latitude: 47.6, longitude: 10.15),
                    Coordinate3D(latitude: 47.5, longitude: 10.2),
                ],
                [
                    Coordinate3D(latitude: 47.52, longitude: 10.25),
                    Coordinate3D(latitude: 47.56, longitude: 10.30),
                    Coordinate3D(latitude: 47.65, longitude: 10.23),
                    Coordinate3D(latitude: 47.6, longitude: 10.22),
                    Coordinate3D(latitude: 47.52, longitude: 10.25),
                ],
            ])!,
            Polygon([[
                Coordinate3D(latitude: 47.56, longitude: 10.1),
                Coordinate3D(latitude: 47.56, longitude: 10.15),
                Coordinate3D(latitude: 47.60, longitude: 10.15),
                Coordinate3D(latitude: 47.65, longitude: 10.15),
                Coordinate3D(latitude: 47.70, longitude: 10.1),
                Coordinate3D(latitude: 47.56, longitude: 10.1),
            ]])!,
        ]))
        let result = try #require(multiPolygon.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("MultiPolygonResult"))
    }

    // MARK: - Ported Turf.js buffer tests

    private func runTurfTest(name: String, result: MultiPolygon) throws {
        let (expected, tolerance) = try Self.expectedArea(name)
        let actual = result.polygons.reduce(0) { $0 + $1.area }
        let ratio = expected > 0 ? actual / expected : (actual == 0 ? 1 : 0)
        #expect(ratio > 1.0 - tolerance && ratio < 1.0 + tolerance,
                "\(name): ratio \(ratio) outside [\(1 - tolerance), \(1 + tolerance)], actual=\(actual), expected=\(expected)")
    }

    private struct TurfFixture: Sendable {
        let name: String
        let loadFeatureCollection: Bool
        let loadGeometryCollection: Bool
        let unionType: BufferUnionType

        init(name: String, loadFeatureCollection: Bool = false, loadGeometryCollection: Bool = false, unionType: BufferUnionType = .individual) {
            self.name = name
            self.loadFeatureCollection = loadFeatureCollection
            self.loadGeometryCollection = loadGeometryCollection
            self.unionType = unionType
        }
    }

    private static let turfFixtures: [TurfFixture] = [
        .init(name: "feature-collection-points", loadFeatureCollection: true),
        .init(name: "geometry-collection-points", loadGeometryCollection: true),
        .init(name: "linestring"),
        .init(name: "multi-linestring"),
        .init(name: "multi-point"),
        .init(name: "multi-polygon"),
        .init(name: "point"),
        .init(name: "polygon-with-holes"),
        .init(name: "northern-polygon"),
        .init(name: "issue-#783", loadFeatureCollection: true),
        .init(name: "issue-#801-Ecuador", loadFeatureCollection: true),
        .init(name: "issue-#801", loadFeatureCollection: true),
        .init(name: "issue-#815"),
        .init(name: "issue-#916", loadFeatureCollection: true),
        .init(name: "north-latitude-points", unionType: .overlapping),
    ]

    @Test(arguments: turfFixtures)
    private func turfFixture(_ fixture: TurfFixture) async throws {
        let params = try Self.bufferParams(fixture.name)
        let geoJson: GeoJson
        if fixture.loadGeometryCollection {
            geoJson = try TestData.geometryCollection(package: "Buffer/in", name: fixture.name)
        } else if fixture.loadFeatureCollection {
            geoJson = try TestData.featureCollection(package: "Buffer/in", name: fixture.name)
        } else {
            geoJson = try TestData.feature(package: "Buffer/in", name: fixture.name)
        }
        try runTurfTest(name: fixture.name, result: try #require(geoJson.buffered(by: params.distance, unionType: fixture.unionType, steps: params.steps)))
    }

    @Test(.disabled("Slow — unions 131 polygons from 66-point LineString buffer"))
    func issue900() async throws {
        let params = try Self.bufferParams("issue-#900")
        try runTurfTest(name: "issue-#900", result: try #require(TestData.feature(package: "Buffer/in", name: "issue-#900").buffered(by: params.distance, steps: params.steps)))
    }

    // MARK: - Negative buffer

    @Test func negativeBuffer() async throws {
        let name = "negative-buffer"
        let json = try TestData.stringFromFile(package: "Buffer/in", name: name)
        guard let data = json.data(using: .utf8),
              let dict = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return }
        let props = dict["properties"] as? [String: Any] ?? [:]
        let radius = props["radius"] as? Double ?? -200.0

        #expect(radius < 0)
        let feature = try TestData.feature(package: "Buffer/in", name: name)
        let geometry = try #require(feature.geometry as? Polygon)
        #expect(geometry.buffered(by: GISTool.convertToMeters(radius, .miles)) == nil)
    }

}
