@testable import GISTools
import Testing

/// Buffer tests using GeoJSON reference files generated by the library
/// itself. The expected outputs are saved in `TestData/Buffer/` and serve
/// as regression guards: they capture the exact geometry (vertex count,
/// area, ring structure) produced by the current buffer + union pipeline.
struct BufferTests {

    // MARK: - Helpers

    private func loadExpected(_ name: String) throws -> MultiPolygon {
        try TestData.multiPolygon(package: "Buffer", name: name)
    }

    private func checkGeometric(_ result: MultiPolygon, _ expected: MultiPolygon) {
        #expect(result.polygons.count == expected.polygons.count)
        let sortedR = result.polygons.sorted(by: { $0.area < $1.area })
        let sortedE = expected.polygons.sorted(by: { $0.area < $1.area })
        for (rp, ep) in zip(sortedR, sortedE) {
            #expect(abs(rp.area - ep.area) < 1.0e-9 * rp.area)
            #expect((rp.innerRings ?? []).count == (ep.innerRings ?? []).count)
        }
        if sortedR.count != sortedE.count || sortedR.count == 0 { return }
        if sortedR.count == 1 {
            // Also check vertex count for single-polygon results
            #expect(sortedR[0].outerRing?.coordinates.count == sortedE[0].outerRing?.coordinates.count)
        }
    }

    private func bufferedFile(_ name: String) throws -> MultiPolygon {
        try loadExpected(name)
    }

    // MARK: - Tests

    @Test func bufferedPoint() async throws {
        let point = Point(Coordinate3D(latitude: 47.56, longitude: 10.22))
        let result = try #require(point.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkGeometric(result, try bufferedFile("PointResult"))
    }

    @Test func bufferedPoints() async throws {
        let multiPoint = try #require(MultiPoint([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(multiPoint.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkGeometric(result, try bufferedFile("MultiPointResult"))
    }

    @Test func bufferedLineShort() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkGeometric(result, try bufferedFile("LineRoundResult"))
    }

    @Test func bufferedLineShortFlatEnds() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkGeometric(result, try bufferedFile("LineFlatResult"))
    }

    @Test func bufferedLineLong() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
            Coordinate3D(latitude: 47.60, longitude: 10.25),
            Coordinate3D(latitude: 47.65, longitude: 10.25),
            Coordinate3D(latitude: 47.70, longitude: 10.2),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkGeometric(result, try bufferedFile("LongLineRoundResult"))
    }

    @Test func bufferedLineLongFlatEnds() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
            Coordinate3D(latitude: 47.60, longitude: 10.25),
            Coordinate3D(latitude: 47.65, longitude: 10.25),
            Coordinate3D(latitude: 47.70, longitude: 10.2),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkGeometric(result, try bufferedFile("LongLineFlatResult"))
    }

    @Test func bufferedLines() async throws {
        let multiLineString = try #require(MultiLineString([
            [
                Coordinate3D(latitude: 47.56, longitude: 10.2),
                Coordinate3D(latitude: 47.56, longitude: 10.25),
            ],
            [
                Coordinate3D(latitude: 47.60, longitude: 10.25),
                Coordinate3D(latitude: 47.65, longitude: 10.25),
                Coordinate3D(latitude: 47.70, longitude: 10.2),
            ],
        ]))
        let result = try #require(multiLineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkGeometric(result, try bufferedFile("MultiLineRoundResult"))
    }

    @Test func bufferedLinesFlatEnds() async throws {
        let multiLineString = try #require(MultiLineString([
            [
                Coordinate3D(latitude: 47.56, longitude: 10.2),
                Coordinate3D(latitude: 47.56, longitude: 10.25),
            ],
            [
                Coordinate3D(latitude: 47.60, longitude: 10.25),
                Coordinate3D(latitude: 47.65, longitude: 10.25),
                Coordinate3D(latitude: 47.70, longitude: 10.2),
            ],
        ]))
        let result = try #require(multiLineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkGeometric(result, try bufferedFile("MultiLineFlatResult"))
    }

    @Test func bufferedPolygon() async throws {
        let polygon = try #require(Polygon([
            [
                Coordinate3D(latitude: 47.5, longitude: 10.2),
                Coordinate3D(latitude: 47.5, longitude: 10.25),
                Coordinate3D(latitude: 47.6, longitude: 10.35),
                Coordinate3D(latitude: 47.7, longitude: 10.25),
                Coordinate3D(latitude: 47.6, longitude: 10.15),
                Coordinate3D(latitude: 47.5, longitude: 10.2),
            ],
            [
                Coordinate3D(latitude: 47.52, longitude: 10.25),
                Coordinate3D(latitude: 47.56, longitude: 10.30),
                Coordinate3D(latitude: 47.65, longitude: 10.23),
                Coordinate3D(latitude: 47.6, longitude: 10.22),
                Coordinate3D(latitude: 47.52, longitude: 10.25),
            ],
        ]))
        let result = try #require(polygon.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkGeometric(result, try bufferedFile("PolygonWithHoleResult"))
    }

    @Test func bufferedMultiPolygon() async throws {
        let multiPolygon = try #require(MultiPolygon([
            Polygon([
                [
                    Coordinate3D(latitude: 47.5, longitude: 10.2),
                    Coordinate3D(latitude: 47.5, longitude: 10.25),
                    Coordinate3D(latitude: 47.6, longitude: 10.35),
                    Coordinate3D(latitude: 47.7, longitude: 10.25),
                    Coordinate3D(latitude: 47.6, longitude: 10.15),
                    Coordinate3D(latitude: 47.5, longitude: 10.2),
                ],
                [
                    Coordinate3D(latitude: 47.52, longitude: 10.25),
                    Coordinate3D(latitude: 47.56, longitude: 10.30),
                    Coordinate3D(latitude: 47.65, longitude: 10.23),
                    Coordinate3D(latitude: 47.6, longitude: 10.22),
                    Coordinate3D(latitude: 47.52, longitude: 10.25),
                ],
            ])!,
            Polygon([[
                Coordinate3D(latitude: 47.56, longitude: 10.1),
                Coordinate3D(latitude: 47.56, longitude: 10.15),
                Coordinate3D(latitude: 47.60, longitude: 10.15),
                Coordinate3D(latitude: 47.65, longitude: 10.15),
                Coordinate3D(latitude: 47.70, longitude: 10.1),
                Coordinate3D(latitude: 47.56, longitude: 10.1),
            ]])!,
        ]))
        let result = try #require(multiPolygon.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkGeometric(result, try bufferedFile("MultiPolygonResult"))
    }

}
