@testable import GISTools
import Testing

/// Buffer tests using GeoJSON reference files generated by `turf.js`
/// (`@turf/buffer` + `@turf/jsts`, JTS offset-curve algorithm).
/// Expected outputs are in `TestData/Buffer/` and serve as an
/// independent ground truth.
///
/// The comparison uses TOTAL AREA within a 5 % tolerance. The turf
/// reference uses a proper offset-curve buffer (more vertices, single
/// merged polygons) while `GISTools` uses a rectangle‑+‑circle‑+‑union
/// approximation, so polygon counts and vertex counts differ deliberately.
struct BufferTests {

    private func loadExpected(_ name: String) throws -> MultiPolygon {
        try TestData.multiPolygon(package: "Buffer", name: name)
    }

    private func checkArea(_ result: MultiPolygon, _ expected: MultiPolygon, tolerance: Double = 0.05) {
        let resultArea = result.polygons.reduce(0) { $0 + $1.area }
        let expectedArea = expected.polygons.reduce(0) { $0 + $1.area }
        if expectedArea == 0 {
            #expect(resultArea == 0)
            return
        }
        let ratio = resultArea / expectedArea
        #expect(ratio > 1.0 - tolerance && ratio < 1.0 + tolerance,
                "Area ratio \(ratio) outside [\(1 - tolerance), \(1 + tolerance)]")
    }

    // MARK: - Tests

    @Test func bufferedPoint() async throws {
        let point = Point(Coordinate3D(latitude: 47.56, longitude: 10.22))
        let result = try #require(point.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("PointResult"))
    }

    @Test func bufferedPoints() async throws {
        let multiPoint = try #require(MultiPoint([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(multiPoint.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("MultiPointResult"))
    }

    @Test func bufferedLineShort() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("LineRoundResult"))
    }

    @Test func bufferedLineShortFlatEnds() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkArea(result, try loadExpected("LineFlatResult"))
    }

    @Test func bufferedLineLong() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
            Coordinate3D(latitude: 47.60, longitude: 10.25),
            Coordinate3D(latitude: 47.65, longitude: 10.25),
            Coordinate3D(latitude: 47.70, longitude: 10.2),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("LongLineRoundResult"), tolerance: 0.15)
    }

    @Test func bufferedLineLongFlatEnds() async throws {
        let lineString = try #require(LineString([
            Coordinate3D(latitude: 47.56, longitude: 10.2),
            Coordinate3D(latitude: 47.56, longitude: 10.25),
            Coordinate3D(latitude: 47.60, longitude: 10.25),
            Coordinate3D(latitude: 47.65, longitude: 10.25),
            Coordinate3D(latitude: 47.70, longitude: 10.2),
        ]))
        let result = try #require(lineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkArea(result, try loadExpected("LongLineFlatResult"), tolerance: 0.25)
    }

    @Test func bufferedLines() async throws {
        let multiLineString = try #require(MultiLineString([
            [
                Coordinate3D(latitude: 47.56, longitude: 10.2),
                Coordinate3D(latitude: 47.56, longitude: 10.25),
            ],
            [
                Coordinate3D(latitude: 47.60, longitude: 10.25),
                Coordinate3D(latitude: 47.65, longitude: 10.25),
                Coordinate3D(latitude: 47.70, longitude: 10.2),
            ],
        ]))
        let result = try #require(multiLineString.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("MultiLineRoundResult"), tolerance: 0.25)
    }

    @Test func bufferedLinesFlatEnds() async throws {
        let multiLineString = try #require(MultiLineString([
            [
                Coordinate3D(latitude: 47.56, longitude: 10.2),
                Coordinate3D(latitude: 47.56, longitude: 10.25),
            ],
            [
                Coordinate3D(latitude: 47.60, longitude: 10.25),
                Coordinate3D(latitude: 47.65, longitude: 10.25),
                Coordinate3D(latitude: 47.70, longitude: 10.2),
            ],
        ]))
        let result = try #require(multiLineString.buffered(by: GISTool.convertToMeters(1000, .meters), lineEndStyle: .flat))
        checkArea(result, try loadExpected("MultiLineFlatResult"))
    }

    @Test func bufferedPolygon() async throws {
        let polygon = try #require(Polygon([
            [
                Coordinate3D(latitude: 47.5, longitude: 10.2),
                Coordinate3D(latitude: 47.5, longitude: 10.25),
                Coordinate3D(latitude: 47.6, longitude: 10.35),
                Coordinate3D(latitude: 47.7, longitude: 10.25),
                Coordinate3D(latitude: 47.6, longitude: 10.15),
                Coordinate3D(latitude: 47.5, longitude: 10.2),
            ],
            [
                Coordinate3D(latitude: 47.52, longitude: 10.25),
                Coordinate3D(latitude: 47.56, longitude: 10.30),
                Coordinate3D(latitude: 47.65, longitude: 10.23),
                Coordinate3D(latitude: 47.6, longitude: 10.22),
                Coordinate3D(latitude: 47.52, longitude: 10.25),
            ],
        ]))
        let result = try #require(polygon.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("PolygonWithHoleResult"))
        result.dump()
    }

    @Test func bufferedMultiPolygon() async throws {
        let multiPolygon = try #require(MultiPolygon([
            Polygon([
                [
                    Coordinate3D(latitude: 47.5, longitude: 10.2),
                    Coordinate3D(latitude: 47.5, longitude: 10.25),
                    Coordinate3D(latitude: 47.6, longitude: 10.35),
                    Coordinate3D(latitude: 47.7, longitude: 10.25),
                    Coordinate3D(latitude: 47.6, longitude: 10.15),
                    Coordinate3D(latitude: 47.5, longitude: 10.2),
                ],
                [
                    Coordinate3D(latitude: 47.52, longitude: 10.25),
                    Coordinate3D(latitude: 47.56, longitude: 10.30),
                    Coordinate3D(latitude: 47.65, longitude: 10.23),
                    Coordinate3D(latitude: 47.6, longitude: 10.22),
                    Coordinate3D(latitude: 47.52, longitude: 10.25),
                ],
            ])!,
            Polygon([[
                Coordinate3D(latitude: 47.56, longitude: 10.1),
                Coordinate3D(latitude: 47.56, longitude: 10.15),
                Coordinate3D(latitude: 47.60, longitude: 10.15),
                Coordinate3D(latitude: 47.65, longitude: 10.15),
                Coordinate3D(latitude: 47.70, longitude: 10.1),
                Coordinate3D(latitude: 47.56, longitude: 10.1),
            ]])!,
        ]))
        let result = try #require(multiPolygon.buffered(by: GISTool.convertToMeters(1000, .meters)))
        checkArea(result, try loadExpected("MultiPolygonResult"))
        result.dump()
    }

}
