import Foundation
@testable import GISTools
import Testing

/// Cross-validation of every pair of built-in projections: for each test
/// point, the coordinates in every projection whose area of use contains
/// it were pre-computed with pyproj/PROJ 9.8.1 (explicit parameterized
/// proj4 strings mirroring the library's parameters, including the
/// Helmert datum transformations in position-vector form — never EPSG
/// codes, so PROJ cannot silently select a better transformation than
/// the library implements). Conversions between two projections follow
/// the library's EPSG:4326 pivot.
///
/// The reference data lives in
/// `Tests/GISToolsTests/TestData/ProjectionMatrix/matrix.csv` (one row per
/// test point and projection) and is machine-generated by
/// `scripts/generate_projection_matrix.py` (regenerate with `--check` to
/// verify); do not edit the values by hand.
struct ProjectionMatrixTests {

    // MARK: - Fixture loading

    /// The CSV fixture lines (the header and blank lines skipped). The
    /// path follows the established `#filePath`-relative test data
    /// mechanism (see `TestData`).
    private static func fixtureLines() throws -> [String] {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("TestData")
            .appendingPathComponent("ProjectionMatrix")
            .appendingPathComponent("matrix")
            .appendingPathExtension("csv")

        let contents = try String(contentsOf: url, encoding: .utf8)
        return contents
            .split(separator: "\n")
            .map(String.init)
            .filter { !$0.isEmpty }
            .filter { !$0.hasPrefix("name,") }
    }

    // MARK: - Fixture model

    private struct MatrixRow {

        let srid: Int
        let x: Double
        let y: Double
        let z: Double
        let tolerance: Double

        /// Extra budget for conversions passing through this CRS's datum
        /// shift, in meters.
        let datumBudget: Double

    }

    private struct MatrixPoint {

        let name: String
        let latitude: Double
        let longitude: Double
        let rows: [MatrixRow]

    }

    /// Parses the CSV fixture (`TestData/ProjectionMatrix/matrix.csv`),
    /// grouping the rows of a test point in file order. The fixture is
    /// small enough that re-parsing per test is negligible.
    private static func points() throws -> [MatrixPoint] {
        let lines = try Self.fixtureLines()
        var points: [MatrixPoint] = []
        var rows: [MatrixRow] = []
        var currentName: String?
        var currentLatitude: Double?
        var currentLongitude: Double?

        func flush() {
            if let name = currentName,
               let latitude = currentLatitude,
               let longitude = currentLongitude,
               rows.count >= 2
            {
                points.append(MatrixPoint(
                    name: name,
                    latitude: latitude,
                    longitude: longitude,
                    rows: rows))
            }
            rows = []
        }

        for line in lines {
            let fields = line.split(separator: ",", omittingEmptySubsequences: false)
            guard fields.count == 10,
                  let latitude = Double(fields[1]),
                  let longitude = Double(fields[2]),
                  let srid = Int(fields[4]),
                  let x = Double(fields[5]),
                  let y = Double(fields[6]),
                  let z = Double(fields[7]),
                  let tolerance = Double(fields[8]),
                  let datumBudget = Double(fields[9])
            else { continue }

            let name = String(fields[0])
            if name != currentName {
                flush()
                currentName = name
                currentLatitude = latitude
                currentLongitude = longitude
            }

            rows.append(MatrixRow(
                srid: srid,
                x: x,
                y: y,
                z: z,
                tolerance: tolerance,
                datumBudget: datumBudget))
        }
        flush()

        return points
    }

    // MARK: - Pair rules

    /// The effective pair tolerance: the larger of the two rows' row
    /// tolerances, plus each side's datum budget (conversions through a
    /// datum shift pick up the Helmert-vs-PROJ ordering difference,
    /// centimeters in lat/lon and up to a decimeter in projected values).
    /// The budgets are meter-valued; degree-unit rows (tolerance below
    /// 1e-5 degrees) divide by the meridian arc per degree.
    private static func pairTolerance(_ source: MatrixRow, _ target: MatrixRow) -> Double {
        let budget = source.datumBudget + target.datumBudget
        let tolerance = max(source.tolerance, target.tolerance)
        guard budget > 0.0 else { return tolerance }

        // Degree-unit rows carry tolerance ~1e-8 or 1e-6; meter-unit rows
        // 1e-3 and above.
        if tolerance < 0.00001 {
            return tolerance + budget / 111_000.0
        }
        return tolerance + budget
    }

    /// The round-trip tolerance: the conversion runs through both
    /// projections' inverse and forward (four steps), so the budget
    /// doubles.
    private static func roundTripTolerance(_ source: MatrixRow, _ target: MatrixRow) -> Double {
        2.0 * pairTolerance(source, target)
    }

    // MARK: - Matrix conversions

    /// Converts every point between every pair of projections containing
    /// it and validates the result against the PROJ reference values.
    @Test
    func matrixConversions() throws {
        for point in try Self.points() {
            for source in point.rows {
                for target in point.rows where target.srid != source.srid {
                    let sourceProjection = try #require(Projection(srid: source.srid))
                    let targetProjection = try #require(Projection(srid: target.srid))

                    // The geocentric projection consumes/produces the
                    // z (ellipsoid height) axis; other projections carry
                    // it through unchanged.
                    let coordinate = Coordinate3D(
                        x: source.x,
                        y: source.y,
                        z: source.srid == 4978 ? source.z : nil,
                        m: 45.0,
                        projection: sourceProjection)
                    let converted = coordinate.projected(to: targetProjection)

                    #expect(
                        abs(converted.x - target.x) < Self.pairTolerance(source, target),
                        "\(point.name): \(source.srid) -> \(target.srid)"
                    )
                    #expect(
                        abs(converted.y - target.y) < Self.pairTolerance(source, target),
                        "\(point.name): \(source.srid) -> \(target.srid)"
                    )
                    #expect(
                        converted.projection.srid == target.srid,
                        "\(point.name): \(source.srid) -> \(target.srid)"
                    )
                    #expect(converted.m == 45.0)
                }
            }
        }
    }

    // MARK: - Round trips

    /// Round-trips every ordered pair: converting from A to B and back
    /// to A must reproduce the source coordinates. Catches inverse-only
    /// regressions.
    @Test
    func matrixRoundTrips() throws {
        for point in try Self.points() {
            for source in point.rows {
                for target in point.rows where target.srid != source.srid {
                    let sourceProjection = try #require(Projection(srid: source.srid))
                    let targetProjection = try #require(Projection(srid: target.srid))

                    let coordinate = Coordinate3D(
                        x: source.x,
                        y: source.y,
                        z: source.srid == 4978 ? source.z : nil,
                        projection: sourceProjection)
                    let converted = coordinate.projected(to: targetProjection)
                    let back = converted.projected(to: sourceProjection)

                    #expect(
                        abs(back.x - source.x) < Self.roundTripTolerance(source, target),
                        "\(point.name): \(source.srid) -> \(target.srid) -> \(source.srid)"
                    )
                    #expect(
                        abs(back.y - source.y) < Self.roundTripTolerance(source, target),
                        "\(point.name): \(source.srid) -> \(target.srid) -> \(source.srid)"
                    )
                }
            }
        }
    }

    // MARK: - Batch equivalence

    /// Validates the batch conversion API on a representative subset of
    /// pairs: the hoisted-setup batch path must produce values identical
    /// to the single-coordinate path (both are compared against the same
    /// PROJ reference rows in `matrixConversions`).
    @Test
    func batchEquivalence() throws {
        for point in try Self.points() {
            for source in point.rows {
                for target in point.rows where target.srid != source.srid {
                    // A deterministic sparse subset keeps the batch test
                    // fast: pairs where both SRIDs are even.
                    guard source.srid % 2 == 0, target.srid % 2 == 0 else { continue }

                    let sourceProjection = try #require(Projection(srid: source.srid))
                    let targetProjection = try #require(Projection(srid: target.srid))

                    let single = [
                        Coordinate3D(
                            x: source.x,
                            y: source.y,
                            z: source.srid == 4978 ? source.z : nil,
                            projection: sourceProjection),
                    ].projected(to: targetProjection)
                    #expect(single.count == 1)

                    #expect(
                        abs(single[0].x - target.x) < Self.pairTolerance(source, target),
                        "\(point.name): batch \(source.srid) -> \(target.srid)"
                    )
                    #expect(
                        abs(single[0].y - target.y) < Self.pairTolerance(source, target),
                        "\(point.name): batch \(source.srid) -> \(target.srid)"
                    )
                }
            }
        }
    }

}
